const Map<String, String> hiIN = {
  // Language Settings
  'select_language': 'भाषा चुनें',
  'search_language': 'भाषा खोजें...',
  'selected_language': 'चयनित भाषा',
  'available_languages': 'उपलब्ध भाषाएं',
  'languages_count': '@count भाषाएं',
  'apply_language': 'भाषा लागू करें',
  'language_changed_success': 'भाषा सफलतापूर्वक बदली गई',
  'language_change_failed': 'भाषा बदलने में विफल: @error',
  // Common
  'home': 'होम',
  'business': 'व्यवसाय',
  'matrimony': 'विवाह',
  'volunteer': 'स्वयंसेवक',
  'settings': 'सेटिंग्स',
  'profile': 'प्रोफाइल',
  'logout': 'लॉगआउट',
  'save': 'सहेजें',
  'cancel': 'रद्द करें',
  'delete': 'हटाएं',
  'edit': 'संपादित करें',
  'update': 'अपडेट करें',
  'submit': 'जमा करें',
  'search': 'खोजें',
  'filter': 'फ़िल्टर',
  'loading': 'लोड हो रहा है...',
  'listening': 'सुन रहा है...',
  'speak_to_search_business': 'व्यवसाय खोजने के लिए बोलें',
  'error': 'त्रुटि',
  'success': 'सफलता',
  'welcome': 'स्वागत है',
  'continue_step': 'जारी रखें',
  'select': 'चुनें',
  'level': 'स्तर',
  'letter': 'पत्र',
  'resume': 'बायोडाटा',
  'info': 'जानकारी',
  'cover_letter': 'कवर लेटर',
  'tap_to_upload_resume': 'बायोडाटा अपलोड करने के लिए टैप करें',
  'additional_information': 'अतिरिक्त जानकारी',

  // Filter Screen
  'filters': 'फ़िल्टर',
  'reset': 'रीसेट',
  'by_criteria': 'मानदंड के अनुसार',
  'by_profile_id': 'प्रोफाइल आईडी के अनुसार',
  'saved_search': 'सहेजी गई खोज',
  'apply_filters': 'फ़िल्टर लागू करें',
  'matrimony_id': 'विवाह आईडी',
  'view_profile': 'प्रोफाइल देखें',
  'your_saved_search': 'आपकी सहेजी गई खोज...',
  'total': 'कुल',
  'search_title': 'खोज शीर्षक',
  'matches': 'मिलान',
  'show_matches': 'मिलान दिखाएं',
  'saved_searches': 'सहेजी गई खोजें',
  'search_by_profile_id': 'प्रोफाइल आईडी से खोजें',

  // Filter Categories
  'basic_details': 'मूल विवरण',
  'professional_details': 'व्यावसायिक विवरण',
  'religion_details': 'धर्म विवरण',
  'family_details': 'पारिवारिक विवरण',
  'location_details': 'स्थान विवरण',
  'lifestyle': 'जीवनशैली',
  'profile_type': 'प्रोफाइल प्रकार',
  'recently_created': 'हाल ही में बनाया गया',

  // Basic Details Filters
  'age': 'आयु',
  'years': 'वर्ष',
  'profile_created_by': 'प्रोफाइल बनाया गया',
  'marital_status': 'वैवाहिक स्थिति',
  'any': 'कोई भी',
  'divorced': 'तलाकशुदा',
  'widow': 'विधवा',
  'single': 'अविवाहित',
  'awaiting_divorce': 'तलाक की प्रतीक्षा में',
  'mother_tongue': 'मातृभाषा',
  'height': 'ऊंचाई (फीट)',
  'weight': 'वजन (किलो)',
  'cm': 'सेमी',
  'physical_status': 'शारीरिक स्थिति',
  'normal': 'सामान्य',
  'doesnt_matter': "कोई फर्क नहीं पड़ता",
  'physically_challenged': 'शारीरिक रूप से अक्षम',

  // Professional Details Filters
  'annual_income': 'वार्षिक आय (लाख)',
  'education': 'शिक्षा',
  'employment_type': 'रोजगार प्रकार',
  'business_owner': 'व्यवसाय स्वामी',
  'defence_sector': 'रक्षा क्षेत्र',
  'government_psu': 'सरकारी / PSU',
  'private_sector': 'निजी क्षेत्र',
  'self_employed': 'स्व-नियोजित',
  'occupation': 'व्यवसाय',
  'airline': 'एयरलाइन',
  'engineering': 'इंजीनियरिंग',
  'it_software': 'आईटी और सॉफ्टवेयर',
  'civil_services': 'सिविल सेवाएं',

  // Religion Details Filters
  'premium': 'प्रीमियम',
  'upgrade_message': 'इन प्रीमियम फ़िल्टर तक पहुंचने के लिए, अभी अपग्रेड करें',
  'profiles_with_horoscope': 'कुंडली वाले प्रोफाइल',
  'matches_with_horoscope': 'जिन्होंने कुंडली जोड़ी है',
  'manglik': 'मांगलिक',
  'dont_know': "पता नहीं",
  'yes': 'हां',
  'no': 'नहीं',

  // Family Details Filters
  'family_status': 'पारिवारिक स्थिति',
  'family_type': 'परिवार का प्रकार',
  'nuclear': 'एकल',
  'joint': 'संयुक्त',
  'not_specified': 'निर्दिष्ट नहीं',
  'family_value': 'पारिवारिक मूल्य',
  'liberal': 'उदार',
  'moderate': 'मध्यम',
  'traditional': 'पारंपरिक',
  'orthodox': 'रूढ़िवादी',

  // Location Details Filters
  'nearby_profiles': 'आस-पास के प्रोफाइल',
  'matches_near_location': 'आपके स्थान के पास मिलान',
  'country': 'देश',
  'citizenship': 'नागरिकता',
  'state': 'राज्य',
  'city': 'शहर',

  // Lifestyle Filters
  'eggetarian': 'अंडाहारी',
  'vegetarian': 'शाकाहारी',
  'non_vegetarian': 'मांसाहारी',
  'smoking_habits': 'धूम्रपान की आदतें',
  'drinking_habits': 'पीने की आदतें',
  'never': 'कभी नहीं',
  'socially': 'सामाजिक रूप से',
  'regularly': 'नियमित रूप से',

  // Profile Type Filters
  'profile_with_photo': 'फोटो के साथ प्रोफाइल',
  'matches_with_photos': 'जिन्होंने फोटो जोड़ी है',
  'dont_show_profile': "प्रोफ़ाइल न दिखाएँ",
  'ignored': 'अनदेखा किया',
  'profiles_ignored': 'आपने जिन प्रोफाइल को अनदेखा किया',
  'shortlisted': 'शॉर्टलिस्ट किया',
  'profiles_shortlisted': 'आपने जिन प्रोफाइल को शॉर्टलिस्ट किया',
  'already_viewed': 'पहले ही देखा',
  'profiles_viewed': 'आपने पहले ही जो प्रोफाइल देखे हैं',
  'already_contacted': 'पहले ही संपर्क किया',
  'profiles_contacted': 'आपने जिन प्रोफाइल से संपर्क किया',

  // Recently Created Filters
  'profile_created': 'प्रोफाइल बनाया गया',
  'all_time': 'सभी समय',
  'today': 'आज',
  'last_7_days': 'पिछले 7 दिन',
  'last_30_days': 'पिछले 30 दिन',
  'one_week': 'एक सप्ताह',
  'one_month': 'एक महीना',

  // Auth - Login Page
  'welcome_back': 'माली सेतु में आपका स्वागत है',
  'login_to_continue': 'अपनी यात्रा जारी रखने के लिए लॉगिन करें',
  'email_label': 'ईमेल',
  'password_label': 'पासवर्ड',
  'remember_me': 'मुझे याद रखें',
  'forget_password': 'पासवर्ड भूल गए',
  'login_button': 'लॉगिन',
  'or': 'या',
  'sign_in_with_google': 'Google से साइन इन करें',
  'dont_have_account': 'खाता नहीं है? ',
  'register': 'पंजीकरण करें',

  // Auth - Register Page
  'create_account': 'खाता बनाएं',
  'fill_details_to_create_account': 'अपना खाता बनाने के लिए विवरण भरें',
  'personal_information': 'व्यक्तिगत जानकारी',
  'full_name': 'पूरा नाम',
  'title': 'शीर्षक',
  'first_name': 'पहला नाम',
  'last_name': 'अंतिम नाम',
  'first_name_required': 'कृपया पहला नाम दर्ज करें',
  'last_name_required': 'कृपया अंतिम नाम दर्ज करें',
  'title_required': 'कृपया एक शीर्षक चुनें',
  'mr': 'श्री.',
  'mrs': 'श्रीमती.',
  'ms': 'सुश्री.',
  'dr': 'डॉ.',
  'prof': 'प्रो.',
  'email_id': 'ईमेल आईडी',
  'date_of_birth': 'जन्म तिथि',
  'mobile_number': 'मोबाइल नंबर',
  'caste_certificate': "जाति प्रमाण पत्र / अन्य प्रमाण / पिता की जाति",
  'tap_to_upload': 'जाति प्रमाण पत्र अपलोड करने के लिए टैप करें',
  'certificate_uploaded': 'जाति प्रमाण पत्र अपलोड किया गया',
  'caste_certificate_criteria': 'फ़ाइल प्रारूप: .jpg, .jpeg, .png, .pdf | अधिकतम फ़ाइल आकार: 5MB',
  'address_details': 'पता विवरण',
  'address': 'पता',
  'nearby_location': 'आस-पास का स्थान',
  'pin_code': 'पिन कोड',
  'district': 'जिला',
  'auto_filled': 'स्वतः भरा गया',
  'road_number': 'सड़क संख्या',
  'sector': 'सेक्टर',
  'destination': 'गंतव्य',
  'company_name': 'कंपनी का नाम',
  'department_name': 'विभाग का नाम',
  'user_type': 'उपयोगकर्ता प्रकार',
  'designation': 'पदनाम',
  'referral_code': 'रेफरल कोड (वैकल्पिक)',
  'referral_optional': '* रेफरल कोड वैकल्पिक है',
  'security': 'सुरक्षा',
  'password': 'पासवर्ड',
  'confirm_password': 'पासवर्ड की पुष्टि करें',
  'register_button': 'पंजीकरण करें',
  'already_have_account': 'पहले से खाता है? ',
  'login_link': 'लॉगिन',

  // Dashboard - Home Page
  'welcome_back_comma': 'वापसी पर स्वागत है,',
  'search_here': 'यहां खोजें...',
  'search_your_business': 'व्यवसाय खोजें',
  'categories': 'श्रेणियां',
  'view_all': 'सभी देखें',
  'register_your_business': 'अपना व्यवसाय पंजीकृत करें',
  'showcase_ideas': 'अपने विचार प्रदर्शित करें और लीड उत्पन्न करें',
  'start_now': 'अभी शुरू करें',
  'register_matrimony': 'विवाह पंजीकरण करें',
  'find_soulmate': 'प्रेम की यात्रा के लिए अपना जीवनसाथी खोजें',
  'join_now': 'अभी शामिल हों',
  'all_categories': 'सभी श्रेणियां',

  // Business Page
  'business_dashboard': 'व्यवसाय डैशबोर्ड',
  'my_business': 'मेरा व्यवसाय',
  'manage_business': 'अपने व्यवसाय का विवरण प्रबंधित करें',
  'register_business': 'व्यवसाय पंजीकृत करें',
  'start_digital_journey': 'अपनी डिजिटल यात्रा शुरू करें',
  'register_now': 'अभी पंजीकरण करें',
  'featured_businesses': 'विशेष व्यवसाय',
  'showing_first_10': 'पहले 10 व्यवसाय दिखा रहे हैं। सभी देखने के लिए \'सभी देखें\' पर टैप करें',
  'businesses_available': 'व्यवसाय उपलब्ध हैं।',
  'all_businesses': 'सभी व्यवसाय',
  'pagination_info': 'पृष्ठांकन जानकारी',
  'page_of': 'पृष्ठ',
  'of': 'of',
  'search_business': 'नाम से व्यवसाय खोजें...',
  'no_businesses_found': 'कोई व्यवसाय नहीं मिला',
  'load_more': 'और लोड करें',
  'all_businesses_loaded': 'सभी व्यवसाय लोड किए गए',
  'business_name': 'व्यवसाय का नाम',
  'location_not_available': 'स्थान उपलब्ध नहीं',
  'active': 'सक्रिय',
  'inactive': 'निष्क्रिय',
  'unknown': 'अज्ञात',

  // Business Details
  'business_details': 'व्यवसाय विवरण',
  'about_business': 'व्यवसाय के बारे में',
  'contact_info': 'संपर्क जानकारी',
  'products': 'उत्पाद',
  'services': 'सेवाएं',
  'jobs': 'नौकरियां',
  'gallery': 'गैलरी',
  'reviews': 'समीक्षाएं',
  'share': 'साझा करें',
  'call': 'कॉल करें',
  'message': 'संदेश',
  'website': 'वेबसाइट',
  'no_description': 'कोई विवरण उपलब्ध नहीं',
  'no_products': 'कोई उत्पाद उपलब्ध नहीं',
  'no_services': 'कोई सेवाएं उपलब्ध नहीं',
  'no_jobs': 'कोई नौकरियां उपलब्ध नहीं',
  'view_details': 'विवरण देखें',
  'apply_now': 'अभी आवेदन करें',
  'add_product': 'उत्पाद जोड़ें',
  'add_service': 'सेवा जोड़ें',
  'create_job': 'नौकरी बनाएं',

  // Job Related
  'job_title': 'नौकरी का शीर्षक',
  'job_description': 'नौकरी का विवरण',
  'job_type': 'नौकरी का प्रकार',
  'salary': 'वेतन',
  'experience': 'अनुभव',
  'location': 'स्थान',
  'posted_on': 'पोस्ट किया गया',
  'apply': 'लागू करें',
  'applications': 'आवेदन',
  'job_details': 'नौकरी विवरण',
  'full_time': 'पूर्णकालिक',
  'part_time': 'अंशकालिक',
  'contract': 'अनुबंध',
  'internship': 'इंटर्नशिप',
  'remote': 'रिमोट',
  'on_site': 'ऑन साइट',
  'hybrid': 'हाइब्रिड',

  // My Business
  'edit_business': 'व्यवसाय संपादित करें',
  'delete_business': 'व्यवसाय हटाएं',
  'business_info': 'व्यवसाय जानकारी',
  'business_category': 'व्यवसाय श्रेणी',
  'business_address': 'व्यवसाय पता',
  'business_phone': 'व्यवसाय फोन',
  'business_email': 'व्यवसाय ईमेल',
  'business_website': 'व्यवसाय वेबसाइट',
  'business_description': 'व्यवसाय विवरण',
  'save_changes': 'परिवर्तन सहेजें',
  'confirm_delete': 'हटाने की पुष्टि करें',
  'delete_business_message': 'क्या आप वाकई इस व्यवसाय को हटाना चाहते हैं?',

  // Job Applications
  'job_applications': 'नौकरी आवेदन',
  'status': 'स्थिति',
  'applied_on': 'आवेदन किया',
  'no_applications': 'कोई आवेदन नहीं मिला',
  'applicant_name': 'आवेदक का नाम',
  'applicant_email': 'ईमेल',
  'applicant_phone': 'फोन',
  'view_resume': 'बायोडाटा देखें',
  'download_resume': 'बायोडाटा डाउनलोड करें',
  'resume_not_uploaded': 'बायोडाटा अपलोड नहीं किया गया',
  'unknown_applicant': 'अज्ञात आवेदक',
  'no_email': 'कोई ईमेल नहीं',
  'review': 'समीक्षा',
  'reject': 'अस्वीकार करें',
  'accept': 'स्वीकार करें',
  'mark_as_reviewed': 'समीक्षित के रूप में चिह्नित करें',
  'update_status': 'स्थिति अपडेट करें',
  'verify_status_change_message': 'क्या आप वाकई @user के लिए स्थिति को @status में बदलना चाहते हैं?',
  'confirm': 'पुष्टि करें',
  'view': 'देखें',
  'accepted': 'स्वीकार किया',
  'rejected': 'अस्वीकृत',
  'reviewed': 'समीक्षित',
  'pending': 'लंबित',
  'job_editor_init_error': 'नौकरी संपादक प्रारंभ नहीं कर सका। कृपया पुनः प्रयास करें।',
  'delete_job_posting': 'नौकरी पोस्टिंग हटाएं',
  'delete_job_confirmation': 'क्या आप वाकई इस नौकरी को हटाना चाहते हैं? इस क्रिया को पूर्ववत नहीं किया जा सकता।',
  'deactivate_job': 'नौकरी निष्क्रिय करें',
  'activate_job': 'नौकरी सक्रिय करें',
  'deactivate_job_confirmation': 'क्या आप वाकई इस नौकरी पोस्टिंग को निष्क्रिय करना चाहते हैं? यह आवेदकों को दिखाई नहीं देगी।',
  'activate_job_confirmation': 'क्या आप वाकई इस नौकरी पोस्टिंग को सक्रिय करना चाहते हैं? यह आवेदकों को दिखाई देगी।',
  'deactivate': 'निष्क्रिय करें',
  'activate': 'सक्रिय करें',
  'edit_job': 'नौकरी संपादित करें',
  'toggle_visibility': 'दृश्यता टॉगल करें',
  'delete_job': 'नौकरी हटाएं',
  'no_title': 'कोई शीर्षक नहीं',
  'unknown_company': 'अज्ञात कंपनी',
  'experience_level': 'स्तर',
  'entry_level': 'प्रवेश',
  'overview': 'अवलोकन',
  'requirements': 'आवश्यकताएं',
  'required_skills': 'आवश्यक कौशल',
  'benefits': 'लाभ',
  'about': 'के बारे में',
  'no_company_info': 'कोई कंपनी जानकारी प्रदान नहीं की गई।',
  'email': 'ईमेल',
  'phone': 'फोन',
  'similar_jobs': 'समान नौकरियां',
  'job_title_fallback': 'नौकरी का शीर्षक',
  'company_fallback': 'कंपनी',
  'view_appliers': 'आवेदकों को देखें',
  'applied': 'आवेदन किया',
  'discover': 'खोजें',
  'members': 'सदस्य',
  'all_matches': 'सभी मिलान',
  'newly_joined': 'नए शामिल',
  'no_matches_found': 'कोई मिलान नहीं मिला',
  'no_more_profiles': 'और कोई प्रोफाइल नहीं',
  'seen_all_matches': 'आपने सभी उपलब्ध मिलान देख लिए हैं',
  'new': 'नया',
  'professional': 'व्यावसायिक',
  'no_name': 'कोई नाम नहीं',
  'unknown_city': 'अज्ञात',



  'waiting_for_approval': 'अनुमोदन की प्रतीक्षा में',
  'name': 'नाम',
  'got_it': 'समझ गया!',
  'are_you_sure_for_logout': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
  'coming_soon': 'जल्द आ रहा है!',
  'choose_your_preferred_language': 'अपनी पसंदीदा भाषा चुनें',
  'coming_soon_msg': 'हम वर्तमान में इस सुविधा पर काम कर रहे हैं।\nयह भविष्य के अपडेट में उपलब्ध होगी!',


  ////  Settings Screen
  'profile & settings': 'प्रोफाइल और सेटिंग्स',
  'user_information': 'उपयोगकर्ता जानकारी',
  'my_profile': 'मेरी प्रोफाइल',
  'app_language': 'ऐप भाषा',
  'user_approval': 'उपयोगकर्ता अनुमोदन',
  'active_user': 'सक्रिय उपयोगकर्ता',
  'active_business': 'सक्रिय व्यवसाय',
  'business_approval': 'व्यवसाय अनुमोदन',
  'business_type': 'व्यवसाय प्रकार',
  'saved_business': 'सहेजा गया व्यवसाय',
  'active_volunteer': 'सक्रिय स्वयंसेवक',
  'volunteer_approval': 'स्वयंसेवक अनुमोदन',
  'volunteer_excel_download': 'स्वयंसेवक एक्सेल डाउनलोड',
  'legal': 'कानूनी',
  'privacy_policy': 'गोपनीयता नीति',
  'terms & conditions': 'नियम और शर्तें',
  'contact_support': 'सहायता से संपर्क करें',
  'app_settings': 'ऐप सेटिंग्स',
  'share_app': 'ऐप साझा करें',
  'confirm_logout': 'लॉगआउट की पुष्टि करें',
  'you_will_be_redirected_to_the_login_screen': 'आपको लॉगिन स्क्रीन पर पुनर्निर्देशित किया जाएगा।',
  'want_to_grow_your_business': 'अपना व्यवसाय बढ़ाना चाहते हैं?',
  'initiative_by': 'पहल द्वारा',
  'anushka_foundation': 'अनुष्का फाउंडेशन',


  'change_password': 'पासवर्ड बदलें',


  // Section Titles
  'basic_information': 'मूल जानकारी',
  'contact_information': 'संपर्क जानकारी',
  'address_information': 'पता जानकारी',

  // Contact fields
  'email_address': 'ईमेल पता',
  'salary_not_specified': 'वेतन निर्दिष्ट नहीं',

  // Address fields
  'street_address': 'सड़क का पता',
  'pincode': 'पिनकोड',

  // Fallback texts
  'name_not_available': 'नाम उपलब्ध नहीं',
  'email_not_available': 'ईमेल उपलब्ध नहीं',
  'not_available': 'उपलब्ध नहीं',


//// change password screen

  'create_new_password': 'एक नया पासवर्ड बनाएं',
  'password_subtitle': 'आपका नया पासवर्ड पिछले पासवर्ड से अलग होना चाहिए',
  'current_password': 'वर्तमान पासवर्ड',
  'new_password': 'नया पासवर्ड',
  'password_guidelines': 'पासवर्ड दिशानिर्देश',
  'password_rule_length': 'कम से कम 8 अक्षर लंबा',
  'password_rule_letters_numbers': 'अक्षर और संख्याएं होनी चाहिए',
  'password_rule_different': 'वर्तमान पासवर्ड से अलग',
  'password_rule_personal': 'व्यक्तिगत जानकारी का उपयोग करने से बचें',




  'update_profile': 'प्रोफाइल अपडेट करें',
  'create_profile': 'प्रोफाइल बनाएं',
  'update_info_desc': 'बेहतर मिलान पाने के लिए अपनी स्वयंसेवक जानकारी अपडेट करें।',
  'fill_info_desc': 'स्वयंसेवक के रूप में शामिल होने के लिए अपनी जानकारी भरें।',
  'skills': 'कौशल',
  'interests': 'रुचियां',
  'bio': 'बायो',
  'bio_hint': 'अपने बारे में बताएं...',
  'location_hint': 'अपना स्थान दर्ज करें',
  'level_hint': 'e.g., Intermediate',
  'availability_hint': 'e.g., Weekends',
  'availability': 'उपलब्धता',
  'add_skill': 'कौशल जोड़ें',
  'skill_hint': 'जैसे: शिक्षण',
  'selected_skills': 'चयनित कौशल',
  'popular_skills': 'लोकप्रिय कौशल',
  'add_interest': 'रुचि जोड़ें',
  'interest_hint': 'e.g. Environment',
  'selected_interests': 'चयनित रुचियां',
  'popular_interests': 'लोकप्रिय रुचियां',
  'no_label': 'कोई लेबल नहीं',




  'community': 'समुदाय',
  'volunteers': 'स्वयंसेवक',
  'my_volunteer_profile': 'मेरी स्वयंसेवक प्रोफाइल',
  'manage_contributions': 'अपने योगदान प्रबंधित करें',
  'no_volunteers_found': 'कोई स्वयंसेवक नहीं मिला',
  'available_volunteers': 'उपलब्ध स्वयंसेवक',
  'found': 'मिला',
  'offline': 'ऑफलाइन',
  'individual_volunteer': 'व्यक्तिगत स्वयंसेवक',
  'unknown_location': 'अज्ञात स्थान',


  'volunteer_profile': 'स्वयंसेवक प्रोफाइल',
  'profile_not_found': 'प्रोफाइल नहीं मिला',
  'about_me': 'मेरे बारे में',
  'no_bio_added': 'अभी तक कोई बायो नहीं जोड़ा गया।',
  'no_skills_listed': 'कोई कौशल सूचीबद्ध नहीं',
  'no_interests_listed': 'कोई रुचियां सूचीबद्ध नहीं',



  'details': 'विवरण',
  'opportunity_not_found': 'अवसर नहीं मिला',
  'volunteer_opportunity': 'स्वयंसेवक अवसर',
  'unknown_organization': 'अज्ञात संगठन',
  'needed': 'आवश्यक',
  'spots': 'स्थान',
  'deadline': 'समय सीमा',
  'about_opportunity': 'इस अवसर के बारे में',
  'contact_person': 'संपर्क व्यक्ति',
  'phone_number': 'फोन नंबर',
  'tbd': 'निर्धारित किया जाना है',



  'notifications': 'सूचनाएं',
  'done': 'पूर्ण',
  'no_notifications': 'कोई सूचना नहीं',
  'notification': 'सूचना',
  'new_notification_message': 'आपके पास एक नई सूचना है',
  'just_now': 'अभी',
  'hours_ago': 'घंटे पहले',
  'minutes_ago': 'मिनट पहले',
  'select_all': 'सभी चुनें',
  'delete_notifications': 'सूचनाएं हटाएं',
  'delete_confirm_message': 'क्या आप वाकई @count सूचनाएं हटाना चाहते हैं?',


  'chat': 'चैट',
  'online': 'ऑनलाइन',
  'type_message': 'एक संदेश लिखें...',
  'no_messages_yet': 'अभी तक कोई संदेश नहीं',
  'start_conversation': 'बातचीत शुरू करने के लिए एक संदेश भेजें',


  'category_details': 'श्रेणी विवरण',
  'category_inactive': 'यह श्रेणी वर्तमान में निष्क्रिय है।',
  'related_businesses': 'संबंधित व्यवसाय',
  'no_business_found': 'इस श्रेणी में कोई व्यवसाय नहीं मिला।',
  'location_na': 'स्थान उपलब्ध नहीं',

  "reset_password": "पासवर्ड रीसेट करें",
  "enter_email_otp": "अपना ईमेल पता दर्ज करें, हम आपको पासवर्ड रीसेट करने के लिए OTP भेजेंगे।",
  "send_otp": "OTP भेजें",
  "email_link_info": "हम आपको पासवर्ड रीसेट करने के लिए ईमेल भेजेंगे",
  "need_help": "मदद चाहिए?",
  "enter_otp_email": "अपने ईमेल पर प्राप्त OTP दर्ज करें और नया पासवर्ड सेट करें",
  "otp": "OTP",
  "enter_6_digit_otp": "6 अंकों का OTP दर्ज करें",
  "reset_password_btn": "पासवर्ड रीसेट करें",
  "didnt_receive_otp": "OTP प्राप्त नहीं हुआ?",
  "resend_otp": "OTP फिर से भेजें",
  "otp_required": "OTP आवश्यक है",
  "otp_invalid": "OTP कम से कम 4 अंकों का होना चाहिए",
  "confirm_password_required": "पासवर्ड की पुष्टि आवश्यक है",
  "passwords_do_not_match": "पासवर्ड मेल नहीं खाते",
  "enter_your_otp": "अपना OTP दर्ज करें",
  "enter_your_password": "अपना पासवर्ड दर्ज करें",
  "enter_your_confirm_password": "अपना पुष्टि पासवर्ड दर्ज करें",

  "verify_your_number": "अपना नंबर सत्यापित करें",
  "enter_otp_mobile": "अपने मोबाइल नंबर पर भेजा गया\n6 अंकों का कोड दर्ज करें",
  "didnt_receive_code": "कोड प्राप्त नहीं हुआ?",
  "resend_in": "{countdown} सेकंड में फिर से भेजें",
  "verify_continue": "सत्यापित करें और जारी रखें",

  "upload_caste_certificate": "जाति प्रमाण पत्र अपलोड करें",
  "referral_code_optional": "रेफरल कोड (वैकल्पिक)",
  "referral_code_note": "* रेफरल कोड वैकल्पिक है",



  'select_image_source': 'छवि स्रोत चुनें',
  'camera': 'कैमरा',
  'product_images': 'उत्पाद छवियां',
  'tap_to_add_images': 'उत्पाद छवियां जोड़ने के लिए टैप करें',
  'camera_or_gallery': 'कैमरा या गैलरी',

  'image_upload_hint': 'फ़ाइल प्रारूप: .jpg, .jpeg, .png | अधिकतम फ़ाइल आकार: 2MB',
  'please_select_at_least_one_image': 'कृपया कम से कम एक छवि चुनें',
  'product_name': 'उत्पाद का नाम',
  'product_description': 'उत्पाद विवरण',
  'product_price': 'उत्पाद मूल्य',
  'create_product': 'उत्पाद बनाएं',
  'creating': 'बना रहे हैं...',
  'please_enter_product_name': 'कृपया उत्पाद का नाम दर्ज करें',
  'please_enter_product_description': 'कृपया उत्पाद विवरण दर्ज करें',
  'please_enter_product_price': 'कृपया उत्पाद मूल्य दर्ज करें',
  'upload_images': 'छवियां अपलोड करें',
  'add': 'जोड़ें',
  'service_name': 'सेवा का नाम',
  'service_description': 'सेवा विवरण',
  'service_price': 'सेवा मूल्य',
  'create_service': 'सेवा बनाएं',
  'please_enter_service_name': 'कृपया सेवा का नाम दर्ज करें',
  'please_enter_service_description': 'कृपया सेवा विवरण दर्ज करें',
  'please_enter_service_price': 'कृपया सेवा मूल्य दर्ज करें',

  'na': 'लागू नहीं',
  'explore_jobs': 'नौकरियां खोजें और आवेदन करना शुरू करें!',
  'go_back': 'वापस जाएं',
  'application_details': 'आवेदन विवरण',
  'no_cover_letter': 'कोई कवर लेटर प्रदान नहीं किया गया',
  'additional_info': 'अतिरिक्त जानकारी',
  'available_online': 'ऑनलाइन उपलब्ध',
  'close': 'बंद करें',
  'edit_profile': 'प्रोफाइल संपादित करें',


  'tap_camera_update_photo': 'फोटो अपडेट करने के लिए टैप करें',
  'personal_details_sub': 'अपनी मूल जानकारी से शुरू करें',
  'gender': 'लिंग',
  'complexion': 'रंग',
  'language': 'भाषा',
  'religious_horoscope': 'धार्मिक कुंडली',
  'religious_horoscope_sub': 'आपकी ज्योतिषीय जानकारी',
  'religion': 'धर्म',
  'caste': 'जाति',
  'star': 'नक्षत्र',
  'raasi': 'राशि',
  'dosh': 'दोष',
  'next': 'अगला',
  'back': 'वापस',
  'education_career': 'शिक्षा करियर',
  'education_career_sub': 'योग्यता और व्यवसाय',
  'highest_qualification': 'उच्चतम योग्यता',
  'college': 'कॉलेज',
  'family_lifestyle': 'परिवार और जीवनशैली',
  'family_lifestyle_sub': 'पारिवारिक पृष्ठभूमि और आदतें',
  'family_class': 'पारिवारिक वर्ग',


  'father_occupation': "पिता का व्यवसाय",
  'mother_occupation': "माता का व्यवसाय",
  'diet': "आहार",
  'smoking': "धूम्रपान",
  'drinking': "शराब सेवन",
  'apply_for_job': "नौकरी के लिए आवेदन करें",

  'salary_range': 'वेतन सीमा',
  "job_category": "नौकरी श्रेणी",
  "application_deadline": "आवेदन की अंतिम तिथि",
  "job_expiry_date": "नौकरी समाप्ति तिथि",
  "skills_required": "आवश्यक कौशल",

// Create Job Post Page
  "update_job_posting": "नौकरी पोस्ट अपडेट करें",
  "create_job_posting": "नौकरी पोस्ट बनाएं",
  "edit_job_details": "नौकरी विवरण संपादित करें",
  "update_job_info": "अपनी नौकरी पोस्ट की जानकारी अपडेट करें",
  "fill_job_details": "नौकरी पोस्ट बनाने के लिए विवरण भरें",
  "job_title_hint": "नौकरी का शीर्षक",
  "job_description_hint": "भूमिका और जिम्मेदारियाँ बताएं",
  "requirements_hint": "आवश्यक कौशल और योग्यता लिखें",
  "salary_range_hint": "₹5,000 - ₹50,000 प्रति माह",
  "salary_required": "वेतन सीमा आवश्यक है",
  "location_required": "स्थान आवश्यक है",
  "deadline_hint": "YYYY-MM-DD",
  "deadline_required": "अंतिम तिथि आवश्यक है",
  "expiry_required": "समाप्ति तिथि आवश्यक है",
  "benefits_perks": "लाभ और सुविधाएँ",
  "add_benefit": "लाभ जोड़ें",
  "benefit_hint": "उदा., स्वास्थ्य बीमा",
  "quick_add_benefits": "त्वरित लाभ जोड़ें:",
  "selected_benefits": "चयनित लाभ:",
  "quick_add_skills": "त्वरित कौशल जोड़ें:",
  "update_job": "नौकरी अपडेट करें",
  "post_job_now": "अभी नौकरी पोस्ट करें",
  "field_required": "आवश्यक है",

// Experience Levels
  "mid": "मध्यम",
  "expert": "विशेषज्ञ",

// Employment Types
  "freelance": "फ्रीलांस",

// Job Categories
  "software_development": "सॉफ्टवेयर डेवलपमेंट",
  "marketing": "मार्केटिंग",
  "sales": "बिक्री",
  "design": "डिज़ाइन",
  "finance": "वित्त",
  "human_resources": "मानव संसाधन",
  "other": "अन्य",
  "enter_job_category": "नौकरी श्रेणी दर्ज करें",
  "job_category_hint": "उदा., कंसल्टिंग, हेल्थकेयर",

// Popular Benefits
  "health_insurance": "स्वास्थ्य बीमा",
  "flexible_working_hours": "लचीले कार्य घंटे",
  "paid_time_off": "सवेतन अवकाश",
  "remote_work_options": "रिमोट कार्य विकल्प",
  "professional_development": "व्यावसायिक विकास",
  "stock_options": "स्टॉक विकल्प",
  "performance_bonus": "प्रदर्शन बोनस",
  "gym_membership": "जिम सदस्यता",
  "free_meals": "मुफ्त भोजन",

// Popular Skills
  "php": "PHP",
  "laravel": "Laravel",
  "mysql": "MySQL",
  "rest_api": "REST API",
  "flutter": "Flutter",
  "dart": "Dart",
  "android": "Android",
  "react_native": "React Native",
  "java": "Java",
  "python": "Python",
  "nodejs": "Node.js",
  "ui_ux_design": "UI/UX डिज़ाइन",

// Messages
  "register_business_first": "कृपया पहले व्यवसाय रजिस्टर/चुनें",
  "business_verification_required": "नौकरी पोस्ट करने के लिए आपका व्यवसाय सत्यापित होना चाहिए। कृपया एडमिन से संपर्क करें।",
  "job_created_success": "नौकरी सफलतापूर्वक बनाई गई",
  "job_updated_success": "नौकरी सफलतापूर्वक अपडेट की गई",
  "job_save_failed": "नौकरी सेव करने में विफल",


  'job_analysis_dashboard': 'नौकरी विश्लेषण डैशबोर्ड',
  'job_statistics': 'नौकरी सांख्यिकी',
  'total_jobs': 'कुल नौकरियां',
  'active_jobs': 'सक्रिय नौकरियां',
  'pending_jobs': 'लंबित नौकरियां',
  'total_applications': 'कुल आवेदन',
  'pending_applications': 'लंबित आवेदन',
  'accepted_applications': 'स्वीकृत आवेदन',
  'application_progress': 'आवेदन प्रगति',
  'application_status_distribution': 'आवेदन स्थिति वितरण',
  'lifetime': 'जीवनकाल',
  'recent_applications': 'हाल के आवेदन',
  'no_recent_applications': 'कोई हाल के आवेदन नहीं मिले',
  'job_application': 'नौकरी आवेदन',



  // Register Business Screen (Hindi)
  "update_business": "व्यवसाय अपडेट करें",
  "business_information": "व्यवसाय जानकारी",
  "business_description_hint": "अपने व्यवसाय और उत्पादों का विवरण दें",
  "opening_time": "खुलने का समय",
  "closing_time": "बंद होने का समय",
  "select_opening_time": "कृपया खुलने का समय चुनें",
  "select_closing_time": "कृपया बंद होने का समय चुनें",
  "business_photos": "व्यवसाय की तस्वीरें",
  "contact_number": "संपर्क नंबर",
  "add_business_photos": "व्यवसाय की तस्वीरें जोड़ें",
  "add_more_photos": "और तस्वीरें जोड़ें",

  // Custom Category Dialog
  "add_custom_category": "कस्टम श्रेणी जोड़ें",
  "enter_category_name": "श्रेणी का नाम दर्ज करें",
  "category_name_hint": "उदा., मेडिकल, कंसल्टिंग",
  "add_category": "श्रेणी जोड़ें",
  "category_added_success": "श्रेणी सफलतापूर्वक जोड़ दी गई",

  // Single Business Details Screen
  "unnamed_business": "अनाम व्यवसाय",
  "verified": "सत्यापित",
  "category": "श्रेणी",
  "open_now": "अभी खुला है:",
  "until": "तक",
  "no_products_found": "कोई उत्पाद नहीं मिला",
  "unknown_product": "अज्ञात उत्पाद",
  "no_services_found": "कोई सेवा नहीं मिली",
  "unknown_service": "अज्ञात सेवा",
  "no_jobs_found": "कोई नौकरी नहीं मिली",
  "verification_status": "सत्यापन स्थिति",
  "business_status": "व्यवसाय स्थिति",
  "total_products": "कुल उत्पाद",
  "total_services": "कुल सेवाएँ",
  "total_value": "कुल मूल्य",
  "created_at": "बनाया गया",
  "last_updated": "अंतिम अपडेट",
  "description": "विवरण",

  'more': 'और',
  'applied_jobs': 'आवेदन की गई नौकरियाँ',
  'search_business_by_name': 'नाम से व्यवसाय खोजें...',





  'my_businesses': 'मेरे व्यवसाय',
  'job_analytics': 'नौकरी विश्लेषण',
  'expand_network': 'अपने व्यवसाय नेटवर्क का विस्तार करें',
  'add_another_business': 'अपनी पहुंच बढ़ाने और अधिक ग्राहकों से जुड़ने के लिए एक और व्यवसाय जोड़ें',
  'add_new_business': 'नया व्यवसाय जोड़ें',
  'revenue': 'राजस्व',
  'delete_confirmation': 'क्या आप वाकई इस व्यवसाय को हटाना चाहते हैं? इस क्रिया को पूर्ववत नहीं किया जा सकता।',




  'blood_group': 'रक्त समूह',
  'referral_name': 'रेफरल नाम',
  'enter_custom_category': 'कस्टम श्रेणी',
  'transaction_history': 'लेन-देन इतिहास',
  'call_now': 'अभी कॉल करें',
  'image_load_failed': 'छवि लोड विफल',
  'error_loading_profile': 'प्रोफाइल लोड करने में त्रुटि',
  'error_loading_profiles': 'प्रोफाइल लोड करने में त्रुटि',
  'retry': 'पुनः प्रयास करें',
  'error_loading': 'लोड करने में त्रुटि',
  'connection_requests': 'कनेक्शन अनुरोध',
  'received': 'प्राप्त',
  'sent': 'भेजा गया',
  'no_received_requests': 'कोई प्राप्त अनुरोध नहीं',
  'send_connection_request': 'कनेक्शन अनुरोध भेजें',
  'partner_preferences': 'साथी प्राथमिकताएं',
  'personal_details': 'व्यक्तिगत विवरण',
  'request_sent': 'अनुरोध भेजा गया',



  'father': 'पिता',
  'mother': 'माता',
  'search_members': 'सदस्य खोजें',

  // Business Registration Validation Messages
  'please_enter_business_name': 'कृपया व्यवसाय का नाम दर्ज करें',
  'please_fill_required_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
  'please_select_business_type': 'कृपया व्यवसाय प्रकार चुनें',
  'please_select_business_category': 'कृपया व्यवसाय श्रेणी चुनें',
  'please_enter_business_description': 'कृपया व्यवसाय विवरण दर्ज करें',
  'please_select_opening_time': 'कृपया खुलने का समय चुनें',
  'please_select_closing_time': 'कृपया बंद होने का समय चुनें',
  'please_enter_contact_number': 'कृपया संपर्क नंबर दर्ज करें',
  'please_enter_email_address': 'कृपया ईमेल पता दर्ज करें',
  'please_enter_website': 'कृपया वेबसाइट दर्ज करें',
  'please_enter_valid_website_url': 'कृपया एक मान्य वेबसाइट URL दर्ज करें',
  'please_add_business_photo': 'कृपया कम से कम एक व्यवसाय फोटो जोड़ें',
  
  'registration_failed': 'पंजीकरण विफल',
  'validation_failed': 'सत्यापन विफल',
  'something_went_wrong': 'कुछ गलत हो गया',
  'unexpected_error_occurred': 'एक अप्रत्याशित त्रुटि हुई',
  'business_updated_successfully': 'व्यवसाय सफलतापूर्वक अपडेट किया गया',
  
  'please_enter_category_name': 'कृपया श्रेणी का नाम दर्ज करें',
  'category_added_successfully': 'श्रेणी सफलतापूर्वक जोड़ी गई',
  'failed_to_add_category': 'श्रेणी जोड़ने में विफल',
  'error_occurred': 'एक त्रुटि हुई',
  
  'no_plans_found_showing_all': 'आपके व्यवसाय प्रकार के लिए कोई विशिष्ट योजना नहीं मिली। सभी योजनाएं दिखा रहे हैं।',
  'failed_to_create_payment_order': 'भुगतान आदेश बनाने में विफल',
  'payment_initialization_failed': 'भुगतान प्रारंभ करना विफल',

  // Job Creation Validation Messages
  'please_enter_job_title': 'कृपया नौकरी का शीर्षक दर्ज करें',
  'please_enter_job_description': 'कृपया नौकरी का विवरण दर्ज करें',
  'please_enter_requirements': 'कृपया आवश्यकताएं दर्ज करें',
  'please_select_job_type': 'कृपया नौकरी का प्रकार चुनें',
  'please_select_experience_level': 'कृपया अनुभव स्तर चुनें',
  'please_select_employment_type': 'कृपया रोजगार प्रकार चुनें',
  'please_select_job_category': 'कृपया नौकरी श्रेणी चुनें',





  'blogs': 'ब्लॉग्स',
  "middle_name": "मध्य नाम",
  'contribute': 'योगदान करें',
  'whatsapp': 'व्हाट्सऐप',
  'invalid_pincode': 'कोई मिलान नहीं',
  'location_information': 'स्थान जानकारी',
  'taluka': 'तालुका / गांव',
  'clear_all': 'सभी साफ करें',
  'enter_pincode': 'पिन कोड दर्ज करें',
  'search_volunteers': 'स्वयंसेवक खोजें',
  'unknown_position': 'अज्ञात पद',
  'unknown_business': 'अज्ञात व्यवसाय',
  'please_enter_cover_letter': 'कृपया अपना कवर लेटर दर्ज करें',
  'please_upload_resume': 'कृपया अपना रेज़्यूमे अपलोड करें',
  'plan_required': 'प्लान आवश्यक है',
  'purchase_business_plan_to_search': 'खोज के लिए बिज़नेस प्लान खरीदें',
  'purchase_now': 'अभी खरीदें',
  'plan_purchased': 'प्लान खरीदा गया',
  'valid_for': 'प्लान खरीदा गया',
  'plan_expired': 'प्लान समाप्त हो गया',
  'product_image': 'उत्पाद छवि',
  'service_image': 'सेवा छवि',
  'start_chat': 'चैट शुरू करें',
  'no_sent_request': 'कोई भेजा गया अनुरोध नहीं',
  'plan_not_purchased': 'प्लान नहीं खरीदा गया',
  'purchase_plan_to_activate': 'सक्रिय करने के लिए प्लान खरीदें',
  'register_business_to_search': 'खोज के लिए अपना व्यवसाय रजिस्टर करें',
  'purchase_plan_to_approve_business': 'अपने व्यवसाय को अप्रूव कराने के लिए प्लान खरीदें',




    "no_transcation_msg": "आपका भुगतान इतिहास यहाँ दिखाई देगा\nजैसे ही आप पहली ट्रांजैक्शन करेंगे",
    "support_center": "सपोर्ट सेंटर",
    "how_can_we_help": "हम आपकी कैसे मदद कर सकते हैं?",
    "ready_assist": "हम आपके सभी प्रश्नों में मदद के लिए तैयार हैं।",
    "quick_reference": "त्वरित संदर्भ",
    "support_availability": "सपोर्ट उपलब्धता",
    "whatsapp_email": "व्हाट्सएप और ईमेल",
    "choose_preferred_way": "अपनी पसंद का तरीका चुनें",
    "chat_whatsapp": "हमारी सपोर्ट टीम से तुरंत चैट करें",
    "email_support": "हमें ईमेल करें, हम जल्द जवाब देंगे",
    "call_support": "सीधे सपोर्ट एजेंट से बात करें",
    "we_here_help": "हम आपकी मदद के लिए यहाँ हैं! 💖",
    "community_initiative": "समुदाय के लिए एक सामाजिक पहल",
    "active_24_7": "24/7 सक्रिय",
    "phone_hours": "सुबह 9:00 – रात 9:00 (IST)",
    "priority_support": "समुदाय आधारित पहल",
    "include_details_tip": "तेज़ समाधान के लिए अपना अकाउंट विवरण जोड़ें",
  "no_transcation": "अभी कोई लेन-देन नहीं है",
  "prioritized_support": "प्राथमिकता प्राप्त सहायता",
  "phone_lines": "फोन सेवा",
  "search_blogs": "ब्लॉग खोजें...",
  "address_info": "पता जानकारी",
  "edit_matrimony_profile": "मैट्रिमोनी प्रोफाइल संपादित करें",
  "subcaste": "उप-जाति",
  "designation_not_added": "पदनाम जोड़ा नहीं गया",
  "error_speech_timeout": "भाषण समय समाप्ति त्रुटि",
  "business_hours": "कार्य समय",








};













