const Map<String, String> mrIN = {
  // Language Settings
  'select_language': 'भाषा निवडा',
  'search_language': 'भाषा शोधा...',
  'selected_language': 'निवडलेली भाषा',
  'available_languages': 'उपलब्ध भाषा',
  'languages_count': '@count भाषा',
  'apply_language': 'भाषा लागू करा',
  'language_changed_success': 'भाषा यशस्वीरित्या बदलली',
  'language_change_failed': 'भाषा बदलण्यास अयशस्वी: @error',


  // Common
  'home': 'मुख्यपृष्ठ',
  'business': 'व्यवसाय',
  'matrimony': 'विवाह',
  'volunteer': 'स्वयंसेवक',
  'settings': 'सेटिंग्ज',
  'profile': 'प्रोफाइल',
  'logout': 'लॉगआउट',
  'save': 'जतन करा',
  'cancel': 'रद्द करा',
  'delete': 'हटवा',
  'edit': 'संपादित करा',
  'update': 'अपडेट करा',
  'submit': 'सबमिट करा',
  'search': 'शोधा',
  'filter': 'फिल्टर',
  'loading': 'लोड होत आहे...',
  'error': 'त्रुटी',
  'success': 'यशस्वी',
  'welcome': 'स्वागत आहे',

  // Filter Screen
  'filters': 'फिल्टर',
  'reset': 'रीसेट',
  'by_criteria': 'निकषानुसार',
  'by_profile_id': 'प्रोफाइल आयडीनुसार',
  'saved_search': 'जतन केलेला शोध',
  'apply_filters': 'फिल्टर लागू करा',
  'matrimony_id': 'विवाह आयडी',
  'view_profile': 'प्रोफाइल पहा',
  'your_saved_search': 'तुमचा जतन केलेला शोध...',
  'total': 'एकूण',
  'search_title': 'शोध शीर्षक',
  'matches': 'जुळण्या',
  'show_matches': 'जुळण्या दाखवा',
  'saved_searches': 'जतन केलेले शोध',
  'search_by_profile_id': 'प्रोफाइल आयडीनुसार शोधा',
  
  // Filter Categories
  'basic_details': 'मूलभूत तपशील',
  'professional_details': 'व्यावसायिक तपशील',
  'religion_details': 'धर्म तपशील',
  'family_details': 'कौटुंबिक तपशील',
  'location_details': 'स्थान तपशील',
  'lifestyle': 'जीवनशैली',
  'profile_type': 'प्रोफाइल प्रकार',
  'recently_created': 'नुकतेच तयार केलेले',
  
  // Basic Details Filters
  'age': 'वय',
  'years': 'वर्षे',
  'profile_created_by': 'प्रोफाइल तयार केले',
  'marital_status': 'वैवाहिक स्थिती',
  'any': 'कोणतेही',
  'divorced': 'घटस्फोटित',
  'widow': 'विधवा',
  'single': 'अविवाहित',
  'awaiting_divorce': 'घटस्फोट प्रलंबित',
  'mother_tongue': 'मातृभाषा',
  'height': 'उंची (फूट)',
  'cm': 'सेमी',
  'physical_status': 'शारीरिक स्थिती',
  'normal': 'सामान्य',
  'doesnt_matter': 'फरक पडत नाही',
  'physically_challenged': 'शारीरिकदृष्ट्या अक्षम',
  
  // Professional Details Filters
  'annual_income': 'वार्षिक उत्पन्न (लाख)',
  'education': 'शिक्षण',
  'employment_type': 'रोजगार प्रकार',
  'business_owner': 'व्यवसाय मालक',
  'defence_sector': 'संरक्षण क्षेत्र',
  'government_psu': 'सरकारी / PSU',
  'private_sector': 'खाजगी क्षेत्र',
  'self_employed': 'स्वयंरोजगार',
  'occupation': 'व्यवसाय',
  'airline': 'विमान सेवा',
  'engineering': 'अभियांत्रिकी',
  'it_software': 'आयटी आणि सॉफ्टवेअर',
  'civil_services': 'नागरी सेवा',
  
  // Religion Details Filters
  'premium': 'प्रीमियम',
  'upgrade_message': 'या प्रीमियम फिल्टरसाठी, आता अपग्रेड करा',
  'profiles_with_horoscope': 'कुंडली असलेले प्रोफाइल',
  'matches_with_horoscope': 'ज्यांनी कुंडली जोडली आहे',
  'manglik': 'मांगलिक',
  'dont_know': 'माहित नाही',
  'yes': 'होय',
  'no': 'नाही',
  
  // Family Details Filters
  'family_status': 'कौटुंबिक स्थिती',
  'family_type': 'कुटुंब प्रकार',
  'nuclear': 'एकल',
  'joint': 'संयुक्त',
  'not_specified': 'निर्दिष्ट नाही',
  'family_value': 'कौटुंबिक मूल्ये',
  'liberal': 'उदारमतवादी',
  'moderate': 'मध्यम',
  'traditional': 'पारंपारिक',
  'orthodox': 'रूढिवादी',
  
  // Location Details Filters
  'nearby_profiles': 'जवळपासचे प्रोफाइल',
  'matches_near_location': 'तुमच्या स्थानाजवळील जुळण्या',
  'country': 'देश',
  'citizenship': 'नागरिकत्व',
  'state': 'राज्य',
  'city': 'शहर',
  
  // Lifestyle Filters
  'eggetarian': 'अंडाहारी',
  'vegetarian': 'शाकाहारी',
  'non_vegetarian': 'मांसाहारी',
  'smoking_habits': 'धूम्रपान सवयी',
  'drinking_habits': 'मद्यपान सवयी',
  'never': 'कधीच नाही',
  'socially': 'सामाजिकरित्या',
  'regularly': 'नियमितपणे',
  
  // Profile Type Filters
  'profile_with_photo': 'फोटो असलेले प्रोफाइल',
  'matches_with_photos': 'ज्यांनी फोटो जोडले आहेत',
  'dont_show_profile': 'प्रोफाइल दाखवू नका',
  'ignored': 'दुर्लक्षित',
  'profiles_ignored': 'तुम्ही दुर्लक्षित केलेले प्रोफाइल',
  'shortlisted': 'निवडलेले',
  'profiles_shortlisted': 'तुम्ही निवडलेले प्रोफाइल',
  'already_viewed': 'आधीच पाहिले',
  'profiles_viewed': 'तुम्ही आधीच पाहिलेले प्रोफाइल',
  'already_contacted': 'आधीच संपर्क केला',
  'profiles_contacted': 'तुम्ही संपर्क केलेले प्रोफाइल',
  
  // Recently Created Filters
  'profile_created': 'प्रोफाइल तयार केले',
  'all_time': 'सर्व काळ',
  'today': 'आज',
  'last_7_days': 'गेले 7 दिवस',
  'last_30_days': 'गेले 30 दिवस',
  'one_week': 'एक आठवडा',
  'one_month': 'एक महिना',

  
  // Auth - Login Page
  'welcome_back': 'पुन्हा स्वागत आहे',
  'login_to_continue': 'तुमचा प्रवास सुरू ठेवण्यासाठी लॉगिन करा',
  'email_label': 'ईमेल',
  'password_label': 'पासवर्ड',
  'remember_me': 'मला लक्षात ठेवा',
  'forget_password': 'पासवर्ड विसरलात?',
  'login_button': 'लॉगिन',
  'or': 'किंवा',
  'sign_in_with_google': 'Google सह साइन इन करा',
  'dont_have_account': 'खाते नाही? ',
  'register': 'नोंदणी करा',
  
  // Auth - Register Page
  'create_account': 'खाते तयार करा',
  'fill_details_to_create_account': 'खाते तयार करण्यासाठी तपशील भरा',
  'personal_information': 'वैयक्तिक माहिती',
  'full_name': 'पूर्ण नाव',
  'title': 'पदवी',
  'first_name': 'पहिले नाव',
  'last_name': 'आडनाव',
  'first_name_required': 'पहिले नाव आवश्यक आहे',
  'last_name_required': 'आडनाव आवश्यक आहे',
  'title_required': 'पदवी आवश्यक आहे',
  'mr': 'श्री.',
  'mrs': 'श्रीमती.',
  'ms': 'सुश्री.',
  'dr': 'डॉ.',
  'prof': 'प्रा.',
  'email_id': 'ईमेल आयडी',
  'date_of_birth': 'जन्मतारीख',
  'mobile_number': 'मोबाइल नंबर',
  'caste_certificate': 'जात प्रमाणपत्र',
  'tap_to_upload': 'जात प्रमाणपत्र अपलोड करण्यासाठी टॅप करा',
  'certificate_uploaded': 'जात प्रमाणपत्र अपलोड केले',
  'caste_certificate_criteria': 'फाईल स्वरूप: .jpg, .jpeg, .png, .pdf | कमाल फाईल आकार: 5MB',
  'address_details': 'पत्ता तपशील',
  'address': 'पत्ता',
  'nearby_location': 'जवळचे स्थान',
  'pin_code': 'पिन कोड',
  'district': 'जिल्हा',
  'auto_filled': 'स्वयं-भरलेले',
  'road_number': 'रस्ता क्रमांक',
  'sector': 'सेक्टर',
  'destination': 'गंतव्य',
  'company_name': 'कंपनीचे नाव',
  'department_name': 'विभागाचे नाव',
  'user_type': 'वापरकर्ता प्रकार',
  'designation': 'पदनाम',
  'referral_code': 'रेफरल कोड (पर्यायी)',
  'referral_optional': '* रेफरल कोड पर्यायी आहे',
  'security': 'सुरक्षा',
  'password': 'पासवर्ड',
  'confirm_password': 'पासवर्ड पुष्टी करा',
  'register_button': 'नोंदणी करा',
  'already_have_account': 'आधीच खाते आहे? ',
  'login_link': 'लॉगिन',
  
  // Dashboard - Home Page
  'welcome_back_comma': 'पुन्हा स्वागत आहे,',
  'search_here': 'येथे शोधा...',
  'categories': 'श्रेणी',
  'view_all': 'सर्व पहा',
  'register_your_business': 'तुमचा व्यवसाय नोंदवा',
  'showcase_ideas': 'तुमच्या कल्पना दाखवा आणि लीड्स तयार करा',
  'start_now': 'आता सुरू करा',
  'register_matrimony': 'विवाह नोंदणी करा',
  'find_soulmate': 'प्रेमाच्या प्रवासासाठी तुमचा जीवनसाथी शोधा',
  'join_now': 'आता सामील व्हा',
  'all_categories': 'सर्व श्रेणी',
  'more': 'अधिक',

  // Business Page
  'business_dashboard': 'व्यवसाय डॅशबोर्ड',
  'my_business': 'माझा व्यवसाय',
  'manage_business': 'तुमच्या व्यवसायाचे तपशील व्यवस्थापित करा',
  'register_business': 'व्यवसाय नोंदवा',
  'start_digital_journey': 'तुमचा डिजिटल प्रवास सुरू करा',
  'register_now': 'आता नोंदणी करा',
  'featured_businesses': 'वैशिष्ट्यीकृत व्यवसाय',
  'showing_first_10': 'पहिले 10 व्यवसाय दाखवत आहे. सर्व पाहण्यासाठी \'सर्व पहा\' वर टॅप करा',
  'businesses_available': 'व्यवसाय उपलब्ध आहेत.',
  'all_businesses': 'सर्व व्यवसाय',
  'pagination_info': 'पृष्ठ माहिती',
  'page_of': 'पृष्ठ',
  'of': 'चे',
  'search_business': 'नावाने व्यवसाय शोधा...',
  'no_businesses_found': 'कोणतेही व्यवसाय सापडले नाहीत',
  'load_more': 'अधिक लोड करा',
  'all_businesses_loaded': 'सर्व व्यवसाय लोड केले',
  'business_name': 'व्यवसायाचे नाव',
  'location_not_available': 'स्थान उपलब्ध नाही',
  'active': 'सक्रिय',
  'inactive': 'निष्क्रिय',
  'unknown': 'अज्ञात',
  
  // Business Details
  'business_details': 'व्यवसाय तपशील',
  'about_business': 'व्यवसायाबद्दल',
  'contact_info': 'संपर्क माहिती',
  'products': 'उत्पादने',
  'services': 'सेवा',
  'jobs': 'नोकऱ्या',
  'gallery': 'गॅलरी',
  'reviews': 'पुनरावलोकने',
  'share': 'शेअर करा',
  'call': 'कॉल करा',
  'message': 'संदेश',
  'website': 'वेबसाइट',
  'no_description': 'वर्णन उपलब्ध नाही',
  'no_products': 'उत्पादने उपलब्ध नाहीत',
  'no_services': 'सेवा उपलब्ध नाहीत',
  'no_jobs': 'नोकऱ्या उपलब्ध नाहीत',
  'view_details': 'तपशील पहा',
  'apply_now': 'आता अर्ज करा',
  'add_product': 'उत्पादन जोडा',
  'add_service': 'सेवा जोडा',
  'create_job': 'नोकरी तयार करा',

  
  // Job Related
  'job_title': 'नोकरी शीर्षक',
  'job_description': 'नोकरी वर्णन',
  'job_type': 'नोकरी प्रकार',
  'salary': 'पगार',
  'experience': 'अनुभव',
  'location': 'स्थान',
  'posted_on': 'पोस्ट केले',
  'apply': 'अर्ज करा',
  'applications': 'अर्ज',
  'job_details': 'नोकरी तपशील',
  'full_time': 'पूर्ण वेळ',
  'part_time': 'अर्धवेळ',
  'contract': 'करार',
  'internship': 'इंटर्नशिप',
  'remote': 'रिमोट',
  'on_site': 'ऑन साइट',
  'hybrid': 'हायब्रिड',
  'coming_soon': 'लवकरच येत आहे!',
  'edit_profile': 'प्रोफाइल संपादित करा',
  'tap_camera_update_photo': 'फोटो अपडेट करण्यासाठी टॅप करा',



  'search_business_by_name': 'व्यवसाय शोधा...',
  'applied_jobs': 'अर्ज केलेल्या नोकऱ्या',
  'salary_not_specified': 'पगार माहिती नाही"',
  'waiting_for_approval': 'मंजुरीसाठी प्रतीक्षा"',
  'name': 'नाव"',
  'got_it': 'समजलं!',
  'gender': 'लिंग',
  'language': 'भाषा',
  'religious_horoscope': 'धर्म / राशी',
  'religious_horoscope_sub': 'तुमची ज्योतिषीय माहिती',
  'religion': 'धर्म',
  'caste': 'जात',
  'star': 'नक्षत्र',
  'raasi': 'राशी',
  'dosh': 'दोष',
  'next': 'पुढे',
  'back': 'मागे',
  'weight': 'वजन (किलो)',
  'education_career': 'शिक्षण आणि करिअर',
  'education_career_sub': 'पात्रता आणि व्यवसाय',
  'highest_qualification': 'सर्वोच्च पात्रता',
  'college': 'कॉलेज',
  'family_lifestyle': 'कौटुंबिक जीवनशैली',
  'family_lifestyle_sub': 'कौटुंबिक पार्श्वभूमी व सवयी',
  'family_class': 'कौटुंबिक वर्ग',
  'father_occupation': "वडिलांचा व्यवसाय" ,
  'mother_occupation': "आईचा व्यवसाय" ,
  'diet': "आहार" ,
  'smoking': "सिगारेट/धूम्रपान" ,
  'drinking': "मद्यपान" ,
  'salary_range'  : 'पगार श्रेणी'  ,
  "job_category" : "नोकरीचे प्रकार",
  "application_deadline"  : "अर्जाची अंतिम तारीख",
  "job_expiry_date" : "नोकरीची कालमर्यादा'",
  "skills_required" :"आवश्यक कौशल्ये",
  "apply_for_job" :"नोकरीसाठी अर्ज करा",
  "continue" :"सुरू ठेवा",
  "letter" :"पत्र",
  "resume" :"बायोडाटा",
  "info" :"माहिती",
  "cover_letter" :"कव्हर लेटर",
  'tap_to_upload_resume': 'रेझ्युमे अपलोड करण्यासाठी टॅप करा',
  'additional_information': 'अतिरिक्त माहिती',






  'complexion': 'त्वचेचा रंग',
  'personal_details_sub': 'तुमची मूलभूत माहितीपासून सुरुवात करा"',
  'personal_details': 'वैयक्तिक तपशील',
  'are_you_sure_for_logout': 'आपण नक्की लॉगआउट करू इच्छिता का?',
  'choose_your_preferred_language': 'आपली प्राधान्याची भाषा निवडा',
  'coming_soon_msg': 'आम्ही सध्या या फिचरवर काम करत आहोत हे भविष्यातील अपडेट्समध्ये उपलब्ध होईल!"',

  // My Business
  'edit_business': 'व्यवसाय संपादित करा',
  'delete_business': 'व्यवसाय हटवा',
  'business_info': 'व्यवसाय माहिती',
  'business_category': 'व्यवसाय श्रेणी',
  'business_address': 'व्यवसाय पत्ता',
  'business_phone': 'व्यवसाय फोन',
  'business_email': 'व्यवसाय ईमेल',
  'business_website': 'व्यवसाय वेबसाइट',
  'business_description': 'व्यवसाय वर्णन',
  'save_changes': 'बदल जतन करा',
  'confirm_delete': 'हटवण्याची पुष्टी करा',
  'delete_business_message': 'तुम्हाला नक्की हा व्यवसाय हटवायचा आहे का?',

  
  // Job Applications
  'job_applications': 'नोकरी अर्ज',
  'status': 'स्थिती',
  'applied_on': 'अर्ज तारीख',
  'no_applications': 'कोणतेही अर्ज सापडले नाहीत',
  'applicant_name': 'अर्जदाराचे नाव',
  'applicant_email': 'ईमेल',
  'applicant_phone': 'फोन',
  'view_resume': 'बायोडेटा पहा',
  'download_resume': 'बायोडेटा डाउनलोड करा',
  'resume_not_uploaded': 'बायोडेटा अपलोड केलेला नाही',
  'unknown_applicant': 'अज्ञात अर्जदार',
  'no_email': 'ईमेल नाही',
  'review': 'पुनरावलोकन',
  'reject': 'नकार द्या',
  'accept': 'स्वीकारा',
  'mark_as_reviewed': 'पुनरावलोकन म्हणून चिन्हांकित करा',
  'update_status': 'स्थिती अपडेट करा',
  'verify_status_change_message': 'तुम्हाला नक्की @user साठी @status स्थिती बदलायची आहे का?',
  'confirm': 'पुष्टी करा',
  'view': 'पहा',
  'accepted': 'स्वीकारले',
  'rejected': 'नाकारले',
  'reviewed': 'तपासले',
  'pending': 'प्रलंबित',
  'job_editor_init_error': 'जॉब एडिटर सुरू करता आला नाही. कृपया पुन्हा प्रयत्न करा.',
  'delete_job_posting': 'नोकरी पोस्टिंग हटवा',
  'delete_job_confirmation': 'तुम्हाला नक्की ही नोकरी हटवायची आहे का? ही कृती पूर्ववत केली जाऊ शकत नाही.',
  'deactivate_job': 'नोकरी निष्क्रिय करा',
  'activate_job': 'नोकरी सक्रिय करा',
  'deactivate_job_confirmation': 'तुम्हाला नक्की ही नोकरी पोस्टिंग निष्क्रिय करायची आहे का? ती यापुढे अर्जदारांना दिसणार नाही.',
  'activate_job_confirmation': 'तुम्हाला नक्की ही नोकरी पोस्टिंग सक्रिय करायची आहे का? ती अर्जदारांना दिसेल.',
  'deactivate': 'निष्क्रिय करा',
  'activate': 'सक्रिय करा',
  'edit_job': 'नोकरी संपादित करा',
  'toggle_visibility': 'दृश्यमानता टॉगल करा',
  'delete_job': 'नोकरी हटवा',
  'no_title': 'शीर्षक नाही',
  'unknown_company': 'अज्ञात कंपनी',
  'experience_level': 'पातळी',
  'entry_level': 'प्रवेश',
  'overview': 'आढावा',
  'requirements': 'आवश्यकता',
  'required_skills': 'आवश्यक कौशल्ये',
  'benefits': 'फायदे',
  'about': 'बद्दल',
  'no_company_info': 'कंपनीची माहिती दिली नाही.',
  'email': 'ईमेल',
  'phone': 'फोन',
  'similar_jobs': 'तत्सम नोकऱ्या',
  'job_title_fallback': 'नोकरी शीर्षक',
  'company_fallback': 'कंपनी',
  'view_appliers': 'अर्जदार पहा',
  'applied': 'अर्ज केला',
  'discover': 'शोधा',
  'members': 'सदस्य',
  'all_matches': 'सर्व जुळण्या',
  'newly_joined': 'नुकतेच सामील झालेले',
  'no_matches_found': 'कोणत्याही जुळण्या सापडल्या नाहीत',
  'no_more_profiles': 'आणखी प्रोफाइल नाहीत',
  'seen_all_matches': 'तुम्ही सर्व उपलब्ध जुळण्या पाहिल्या आहेत',
  'new': 'नवीन',
  'professional': 'व्यावसायिक',
  'no_name': 'नाव नाही',
  'unknown_city': 'अज्ञात',


  'profile & settings': 'प्रोफाइल आणि सेटिंग्स',
  'user_information': 'वापरकर्ता माहिती',
  'my_profile': 'माझे प्रोफाइल',
  'app_language': 'ॲप भाषा',
  'user_approval': 'वापरकर्ता मंजुरी',
  'active_user': 'सक्रिय वापरकर्ता',
  'active_business': 'सक्रिय व्यवसाय',
  'business_approval': 'व्यवसाय मंजुरी',
  'business_type': 'व्यवसाय प्रकार',
  'saved_business': 'जतन केलेला व्यवसाय',
  'active_volunteer': 'सक्रिय स्वयंसेवक',
  'volunteer_approval': 'स्वयंसेवक मंजुरी',
  'volunteer_excel_download': 'स्वयंसेवक एक्सेल डाउनलोड',
  'legal': 'कायदेशीर',
  'privacy_policy': 'गोपनीयता धोरण',
  'terms & conditions': 'अटी व शर्ती',
  'contact_support': 'सहाय्याशी संपर्क साधा',
  'app_settings': 'ॲप सेटिंग्स',
  'share_app': 'ॲप शेअर करा',
  'confirm_logout': 'लॉगआउटची पुष्टी करा',
  'you_will_be_redirected_to_the_login_screen': 'आपल्याला लॉगिन स्क्रीनवर पुनर्निर्देशित केले जाईल.',
  'want_to_grow_your_business': 'आपला व्यवसाय वाढवायचा आहे का?',
  'initiative_by': 'उपक्रम',
  'anushka_foundation': 'अनुष्का फाउंडेशन',


  'change_password': 'पासवर्ड बदला',


  // Section Titles
  'basic_information': 'मूलभूत माहिती',
  'contact_information': 'संपर्क माहिती',
  'address_information': 'पत्ता माहिती',

  // Contact fields
  'email_address': 'ई-मेल पत्ता',

  // Address fields
  'street_address': 'रस्त्याचा पत्ता',
  'pincode': 'पिनकोड',

  // Fallback texts
  'name_not_available': 'नाव उपलब्ध नाही',
  'email_not_available': 'ई-मेल उपलब्ध नाही',
  'not_available': 'उपलब्ध नाही',


// change password screen

  'create_new_password': 'नवीन पासवर्ड तयार करा',
  'password_subtitle': 'आपला नवीन पासवर्ड मागील पासवर्डपेक्षा वेगळा असावा',

  // Form labels
  'current_password': 'सध्याचा पासवर्ड',
  'new_password': 'नवीन पासवर्ड',

  // Guidelines
  'password_guidelines': 'पासवर्ड मार्गदर्शक सूचना',
  'password_rule_length': 'किमान ८ अक्षरे असावीत',
  'password_rule_letters_numbers': 'अक्षरे आणि अंक असणे आवश्यक आहे',
  'password_rule_different': 'सध्याच्या पासवर्डपेक्षा वेगळा असावा',
  'password_rule_personal': 'वैयक्तिक माहिती वापरणे टाळा',




  'update_profile': 'प्रोफाइल अपडेट करा',
  'create_profile': 'प्रोफाइल तयार करा',
  'update_info_desc': 'चांगल्या जुळण्यांसाठी आपली स्वयंसेवी माहिती अपडेट करा.',
  'fill_info_desc': 'स्वयंसेवक म्हणून सामील होण्यासाठी आपली माहिती भरा.',
  'skills': 'कौशल्ये',
  'interests': 'स्वारस्ये',
  'bio': 'बायो',
  'bio_hint': 'आपल्या विषयी सांगा...',
  'location_hint': 'उदा., पुणे, महाराष्ट्र',
  'availability': 'उपलब्धता',
  'add_skill': 'कौशल्य जोडा',
  'skill_hint': 'उदा. शिक्षण',
  'selected_skills': 'निवडलेली कौशल्ये',
  'popular_skills': 'लोकप्रिय कौशल्ये',
  'add_interest': 'स्वारस्य जोडा',
  'interest_hint': 'उदा. पर्यावरण',
  'selected_interests': 'निवडलेली स्वारस्ये',
  'popular_interests': 'लोकप्रिय स्वारस्ये',
  'no_label': 'लेबल नाही',


  'community': 'समुदाय',
  'volunteers': 'स्वयंसेवक',
  'my_volunteer_profile': 'माझे स्वयंसेवक प्रोफाइल',
  'manage_contributions': 'आपले योगदान व्यवस्थापित करा',
  'no_volunteers_found': 'कोणतेही स्वयंसेवक सापडले नाहीत',
  'available_volunteers': 'उपलब्ध स्वयंसेवक',
  'found': 'सापडले',
  'offline': 'ऑफलाइन',
  'individual_volunteer': 'वैयक्तिक स्वयंसेवक',
  'unknown_location': 'अज्ञात स्थान',


  'volunteer_profile': 'स्वयंसेवक प्रोफाइल',
  'profile_not_found': 'प्रोफाइल सापडले नाही',
  'about_me': 'माझ्याबद्दल',
  'no_bio_added': 'अजून माहिती जोडलेली नाही.',
  'no_skills_listed': 'कोणतीही कौशल्ये नमूद केलेली नाहीत',
  'no_interests_listed': 'कोणत्याही आवडी नमूद केलेल्या नाहीत',


  'details': 'तपशील',
  'opportunity_not_found': 'संधी सापडली नाही',
  'volunteer_opportunity': 'स्वयंसेवक संधी',
  'unknown_organization': 'अज्ञात संस्था',
  'needed': 'आवश्यक',
  'spots': 'जागा',
  'deadline': 'अंतिम तारीख',
  'about_opportunity': 'या संधीबद्दल',
  'contact_person': 'संपर्क व्यक्ती',
  'phone_number': 'फोन नंबर',
  'tbd': 'निश्चित नाही',


  'notifications': 'सूचना',
  'done': 'पूर्ण',
  'no_notifications': 'कोणत्याही सूचना नाहीत',
  'notification': 'सूचना',
  'new_notification_message': 'आपल्याला नवीन सूचना आली आहे',
  'just_now': 'आत्ता',
  'hours_ago': 'तासांपूर्वी',
  'minutes_ago': 'मिनिटांपूर्वी',
  'select_all': 'सर्व निवडा',
  'delete_notifications': 'सूचना हटवा',
  'delete_confirm_message': 'आपण @count सूचना हटवू इच्छिता का?',



  'chat': 'चॅट',
  'online': 'ऑनलाइन',
  'type_message': 'संदेश लिहा...',
  'no_messages_yet': 'अजून कोणतेही संदेश नाहीत',
  'start_conversation': 'संभाषण सुरू करण्यासाठी संदेश पाठवा',


  'category_details': 'श्रेणी तपशील',
  'category_inactive': 'ही श्रेणी सध्या निष्क्रिय आहे.',
  'related_businesses': 'संबंधित व्यवसाय',
  'no_business_found': 'या श्रेणीमध्ये कोणतेही व्यवसाय सापडले नाहीत.',
  'location_na': 'स्थान उपलब्ध नाही',



  "reset_password": "पासवर्ड रीसेट करा",
  "enter_email_otp": "आपला ईमेल पत्ता प्रविष्ट करा आणि आम्ही आपला पासवर्ड रीसेट करण्यासाठी OTP पाठवू.",
  "send_otp": "OTP पाठवा",
  "email_link_info": "आम्ही आपल्याला पासवर्ड रीसेट करण्यासाठी लिंक ईमेल करू.",
  "need_help": "मदतीची गरज आहे?",
  "enter_otp_email": "आपल्याला ईमेलवर प्राप्त OTP प्रविष्ट करा आणि आपला नवीन पासवर्ड सेट करा",
  "otp": "OTP",
  "enter_6_digit_otp": "6-अंकी OTP प्रविष्ट करा",
  "reset_password_btn": "पासवर्ड रीसेट करा",
  "didnt_receive_otp": "OTP प्राप्त झाला नाही का?",
  "resend_otp": "OTP पुन्हा पाठवा",
  "otp_required": "OTP आवश्यक आहे",
  "otp_invalid": "OTP किमान 4 अंकी असावा",
  "confirm_password_required": "पासवर्डची पुष्टी करणे आवश्यक आहे",
  "passwords_do_not_match": "पासवर्ड जुळत नाहीत",
  "enter_your_otp": "तुमचा OTP प्रविष्ट करा",
  "enter_your_password": "तुमचा पासवर्ड प्रविष्ट करा",
  "enter_your_confirm_password": "तुमच्या पासवर्डची पुष्टी प्रविष्ट करा",




  "verify_your_number": "आपला नंबर सत्यापित करा",
  "enter_otp_mobile": "आपल्या मोबाईल नंबरवर पाठवलेला 6-अंकी कोड प्रविष्ट करा",
  "didnt_receive_code": "कोड प्राप्त झाला नाही का?",
  "resend_in": "{countdown} सेकंदांत पुन्हा पाठवा",
  "verify_continue": "सत्यापित करा आणि पुढे जा",




  "upload_caste_certificate": "जात प्रमाणपत्र अपलोड करा",
  "referral_code_optional": "रेफरल कोड (ऐच्छिक)",
  "referral_code_note": "* रेफरल कोड ऐच्छिक आहे",




  'select_image_source': 'प्रतिमा स्रोत निवडा',
  'camera': 'कॅमेरा',
  'product_images': 'उत्पादन प्रतिमा',
  'tap_to_add_images': 'उत्पादन प्रतिमा जोडण्यासाठी टॅप करा',
  'camera_or_gallery': 'कॅमेरा किंवा गॅलरी',
  'product_name': 'उत्पादनाचे नाव',
  'product_description': 'उत्पादनाचे वर्णन',
  'product_price': 'उत्पादनाची किंमत',
  'create_product': 'उत्पादन तयार करा',
  'creating': 'तयार करत आहे...',



  'upload_images': 'प्रतिमा अपलोड करा',
  'add': 'जोडा',
  'service_name': 'सेवेचे नाव',
  'service_description': 'सेवेचे वर्णन',
  'service_price': 'सेवेची किंमत',
  'create_service': 'सेवा तयार करा',




  'my_applications': 'माझ्या अर्ज',
  'unknown_position': 'अज्ञात पद',
  'unknown_business': 'अज्ञात व्यवसाय',
  'approved': 'मान्यता दिली',
  'declined': 'नाकारले',
  'na': 'लागू नाही',
  'explore_jobs': 'नोकऱ्या शोधा आणि अर्ज करायला सुरुवात करा!',
  'go_back': 'परत जा',
  'application_details': 'अर्जाचे तपशील',
  'no_cover_letter': 'कव्हर लेटर उपलब्ध नाही',
  'additional_info': 'अतिरिक्त माहिती',
  'available_online': 'ऑनलाईन उपलब्ध',
  'close': 'बंद करा',


  // Create Job Post Page
  "update_job_posting": "नोकरी पोस्टिंग अपडेट करा",
  "create_job_posting": "नोकरी पोस्टिंग तयार करा",
  "edit_job_details": "नोकरी तपशील संपादित करा",
  "update_job_info": "तुमच्या नोकरी पोस्टिंगची माहिती अपडेट करा",
  "fill_job_details": "तुमची नोकरी पोस्टिंग तयार करण्यासाठी तपशील भरा",
  "job_title_hint": "नोकरी शीर्षक",
  "job_description_hint": "भूमिका, जबाबदारी वर्णन करा",
  "requirements_hint": "आवश्यक कौशल्ये, पात्रता यादी करा",
  "salary_range_hint": "₹5,000 - ₹50,000 प्रति महिना",
  "salary_required": "पगार श्रेणी आवश्यक आहे",
  "location_required": "स्थान आवश्यक आहे",
  "deadline_hint": "YYYY-MM-DD",
  "deadline_required": "अंतिम तारीख आवश्यक आहे",
  "expiry_required": "समाप्ती तारीख आवश्यक आहे",
  "benefits_perks": "फायदे आणि सुविधा",
  "add_benefit": "फायदा जोडा",
  "benefit_hint": "उदा., आरोग्य विमा",
  "quick_add_benefits": "त्वरित फायदे जोडा:",
  "selected_benefits": "निवडलेले फायदे:",
  "quick_add_skills": "त्वरित कौशल्ये जोडा:",
  "update_job": "नोकरी अपडेट करा",
  "post_job_now": "आता नोकरी पोस्ट करा",
  "field_required": "आवश्यक आहे",
  
  // Job Types

  // Experience Levels
  "mid": "मध्यम",
  "expert": "तज्ञ",
  
  // Employment Types
  "freelance": "फ्रीलान्स",
  
  // Job Categories
  "software_development": "सॉफ्टवेअर विकास",
  "marketing": "विपणन",
  "sales": "विक्रय",
  "design": "डिजाइन",
  "finance": "वित्त",
  "human_resources": "मानव संसाधन",
  "other": "अन्य",
  "enter_job_category": "नोकरी श्रेणी प्रविष्ट करा",
  "job_category_hint": "उदा., सल्लागारी, स्वास्थ्यसेवा",
  
  // Popular Benefits
  "health_insurance": "आरोग्य विमा",
  "flexible_working_hours": "लवचिक कामाचे तास",
  "paid_time_off": "सशुल्क सुट्टी",
  "remote_work_options": "रिमोट कामाचे पर्याय",
  "professional_development": "व्यावसायिक विकास",
  "stock_options": "स्टॉक पर्याय",
  "performance_bonus": "कामगिरी बोनस",
  "gym_membership": "जिम सदस्यत्व",
  "free_meals": "मोफत जेवण",
  
  // Popular Skills
  "php": "PHP",
  "laravel": "Laravel",
  "mysql": "MySQL",
  "rest_api": "REST API",
  "flutter": "Flutter",
  "dart": "Dart",
  "android": "Android",
  "react_native": "React Native",
  "java": "Java",
  "python": "Python",
  "nodejs": "Node.js",
  "ui_ux_design": "UI/UX डिझाइन",
  
  // Messages
  "register_business_first": "कृपया प्रथम व्यवसाय नोंदवा/निवडा",
  "business_verification_required": "नोकरी पोस्ट करण्यासाठी तुमचा व्यवसाय सत्यापित असणे आवश्यक आहे. कृपया प्रशासकाशी संपर्क साधा.",
  "job_created_success": "नोकरी पोस्टिंग यशस्वीरित्या तयार केली",
  "job_updated_success": "नोकरी पोस्टिंग यशस्वीरित्या अपडेट केली",
  "job_save_failed": "नोकरी पोस्टिंग जतन करण्यात अयशस्वी",




  'job_analysis_dashboard': 'नोकरी विश्लेषण डॅशबोर्ड',
  'job_statistics': 'नोकरी आकडेवारी',
  'total_jobs': 'एकूण नोकऱ्या',
  'active_jobs': 'सक्रिय नोकऱ्या',
  'pending_jobs': 'प्रलंबित नोकऱ्या',
  'total_applications': 'एकूण अर्ज',
  'pending_applications': 'प्रलंबित अर्ज',
  'accepted_applications': 'स्वीकारलेले अर्ज',
  'application_progress': 'अर्जाची प्रगती',
  'application_status_distribution': 'अर्ज स्थितीचे वितरण',
  'lifetime': 'आयुष्यभर',
  'recent_applications': 'अलीकडील अर्ज',
  'no_recent_applications': 'अलीकडील कोणतेही अर्ज सापडले नाहीत',
  'job_application': 'नोकरी अर्ज',


  // Register Business Screen
  "update_business": "व्यवसाय अपडेट करा",
  "business_information": "व्यवसाय माहिती",
  "business_description_hint": "तुमच्या व्यवसाय, उत्पादनांचे वर्णन करा",
  "opening_time": "सुरुवातीची वेळ",
  "closing_time": "बंद होण्याची वेळ",
  "select_opening_time": "कृपया सुरुवातीची वेळ निवडा",
  "select_closing_time": "कृपया बंद होण्याची वेळ निवडा",
  "business_photos": "व्यवसाय फोटो",
  "contact_number": "संपर्क नंबर",
  "add_business_photos": "व्यवसाय फोटो जोडा",
  "add_more_photos": "अधिक फोटो जोडा",

  // Custom Category Dialog
  "add_custom_category": "कस्टम श्रेणी जोडा",
  "enter_category_name": "श्रेणीचे नाव प्रविष्ट करा",
  "category_name_hint": "उदा., वैद्यकीय, सल्लागारी",
  "add_category": "श्रेणी जोडा",
  "category_added_success": "श्रेणी यशस्वीरित्या जोडली",

  // Single Business Details Screen
  "unnamed_business": "अनामित व्यवसाय",
  "verified": "सत्यापित",
  "category": "श्रेणी",
  "open_now": "आता उघडे:",
  "until": "पर्यंत",
  "no_products_found": "कोणतीही उत्पादने सापडली नाहीत",
  "unknown_product": "अज्ञात उत्पादन",
  "no_services_found": "कोणत्याही सेवा सापडल्या नाहीत",
  "unknown_service": "अज्ञात सेवा",
  "no_jobs_found": "कोणत्याही नोकऱ्या सापडल्या नाहीत",
  "verification_status": "सत्यापन स्थिती",
  "business_status": "व्यवसाय स्थिती",
  "total_products": "एकूण उत्पादने",
  "total_services": "एकूण सेवा",
  "total_value": "एकूण मूल्य",
  "created_at": "तयार केले",
  "last_updated": "शेवटचे अपडेट",
  "description": "वर्णन",



  'my_businesses': 'माझे व्यवसाय',
  'job_analytics': 'नोकरी विश्लेषण',
  'expand_network': 'तुमच्या व्यवसायाचे नेटवर्क वाढवा',
  'add_another_business': 'आपली पोहोच वाढवण्यासाठी आणखी व्यवसाय जोडा आणि अधिक ग्राहकांशी कनेक्ट व्हा',
  'add_new_business': 'नवीन व्यवसाय जोडा',
  'revenue': 'उत्पन्न',
  'delete_confirmation': 'आपण नक्कीच हा व्यवसाय हटवू इच्छिता का? ही क्रिया पूर्ववत करता येणार नाही.',


  'blood_group': 'रक्तगट',
  'referral_name': 'संदर्भ देणाऱ्याचे नाव',
  'enter_custom_category': 'सानुकूल श्रेणी प्रविष्ट करा',
  'transaction_history' : 'व्यवहार इतिहास',
  'call_now' : 'आता कॉल करा',
  'image_load_failed': 'प्रतिमा लोड करण्यात अयशस्वी',
  'error_loading_profile': 'प्रोफाइल लोड करण्यात त्रुटी',
  'error_loading_profiles': 'प्रोफाइल लोड करण्यात त्रुटी',
  'retry': 'पुन्हा प्रयत्न करा',
  'error_loading': 'लोड करण्यात त्रुटी',
  'connection_requests': 'कनेक्शन विनंत्या',
  'received': 'प्राप्त झालेले',
  'sent': 'पाठवलेले',
  'no_received_requests': 'प्राप्त विनंत्या नाहीत',
  'send_connection_request': 'संपर्क विनंती पाठवा',
  'partner_preferences': 'जोडीदाराच्या अपेक्षा',
  'request_sent': 'विनंती पाठवली',

  'father' : 'बाबा',
  'mother' : 'आई',
  'search_members' : 'सदस्य शोधा',

  // Business Registration Validation Messages
  'please_enter_business_name': 'कृपया व्यवसायाचे नाव प्रविष्ट करा',
  'please_fill_required_fields': 'कृपया सर्व आवश्यक फील्ड भरा',
  'please_select_business_type': 'कृपया व्यवसायाचा प्रकार निवडा',
  'please_select_business_category': 'कृपया व्यवसायाची श्रेणी निवडा',
  'please_enter_business_description': 'कृपया व्यवसायाचे वर्णन प्रविष्ट करा',
  'please_select_opening_time': 'कृपया उघडण्याची वेळ निवडा',
  'please_select_closing_time': 'कृपया बंद होण्याची वेळ निवडा',
  'please_enter_contact_number': 'कृपया संपर्क क्रमांक प्रविष्ट करा',
  'please_enter_email_address': 'कृपया ईमेल पत्ता प्रविष्ट करा',
  'please_enter_website': 'कृपया वेबसाइट प्रविष्ट करा',
  'please_enter_valid_website_url': 'कृपया वैध वेबसाइट URL प्रविष्ट करा',
  'please_add_business_photo': 'कृपया किमान एक व्यवसाय फोटो जोडा',
  
  'registration_failed': 'नोंदणी अयशस्वी',
  'validation_failed': 'प्रमाणीकरण अयशस्वी',
  'something_went_wrong': 'काहीतरी चूक झाली',
  'unexpected_error_occurred': 'अनपेक्षित त्रुटी आली',
  'business_updated_successfully': 'व्यवसाय यशस्वीरित्या अपडेट केला',
  
  'please_enter_category_name': 'कृपया श्रेणीचे नाव प्रविष्ट करा',
  'category_added_successfully': 'श्रेणी यशस्वीरित्या जोडली',
  'failed_to_add_category': 'श्रेणी जोडण्यात अयशस्वी',
  'error_occurred': 'त्रुटी आली',
  
  'no_plans_found_showing_all': 'तुमच्या व्यवसाय प्रकारासाठी कोणतीही विशिष्ट योजना आढळली नाही. सर्व योजना दाखवत आहे.',
  'failed_to_create_payment_order': 'पेमेंट ऑर्डर तयार करण्यात अयशस्वी',
  'payment_initialization_failed': 'पेमेंट सुरू करण्यात अयशस्वी',

  // Job Creation Validation Messages
  'please_enter_job_title': 'कृपया नोकरीचे शीर्षक प्रविष्ट करा',
  'please_enter_job_description': 'कृपया नोकरीचे वर्णन प्रविष्ट करा',
  'please_enter_requirements': 'कृपया आवश्यकता प्रविष्ट करा',
  'please_select_job_type': 'कृपया नोकरीचा प्रकार निवडा',
  'please_select_experience_level': 'कृपया अनुभव स्तर निवडा',
  'please_select_employment_type': 'कृपया रोजगार प्रकार निवडा',
  'please_select_job_category': 'कृपया नोकरी श्रेणी निवडा',


  'blogs' : "ब्लॉग्स",
  'contribute' : "योगदान द्या",
  'clear_all' : "सर्व हटवा",
  'whatsapp' : "व्हॉट्सअ‍ॅप",
  'invalid_pincode' : "अयोग्य पिनकोड",
  'location_information' : "स्थान माहिती",
  'taluka' : "तालुका",
  'search_volunteers' : "स्वयंसेवक शोधा",
};








